/*
 * This file is part of physengine.
 * Copyright (c) 2013 Rostislav Pehlivanov <atomnuker@gmail.com>
 * 
 * physengine is free software: you can redistribute it and/or modify *
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * physengine is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with physengine.  If not, see <http://www.gnu.org/licenses/>.
 */
#include <stdio.h>
#include <string.h>
#include <stdbool.h>
#include "config.h"
#include "options.h"
#include "physics.h"
#include "out_xyz.h"
#include "msg_phys.h"
#include "physics_aux.h"

#define FILENAME "system"
#define EXT "xyz"

int toxyz(data *object)
{
	char filetodump[120];
	snprintf(filetodump, sizeof(filetodump),
			 "%s_%0.2Lf.%s", FILENAME, t_stats[1]->progress, EXT);
	FILE *out = fopen(filetodump, "w");
	pprintf(PRI_ESSENTIAL, "Created %s\n", filetodump);
	fprintf(out, "%u\n", option->obj + 1);
	fprintf(out, "#Generated by %s\n", PACKAGE_STRING);
	for(int i = 1; i < option->obj + 1; i++) {
		fprintf(out, "%s %f %f %f\n", atom_prop[object[i].atomnumber].name,\
				(float)object[i].pos[0], (float)object[i].pos[1],\
				(float)object[i].pos[2]);
	}
	fclose(out);
	return 0;
}
